#spring:
spring:
  application:
    name: ms-operator
  jpa:
    database: MYSQL
    show-sql: true
    properties:
     hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/safepeople
    username: ${DB_USER:root}
    password: ${DB_PASS:Ll@n0s2025}  #cambiar clave

  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      platform: mysql
      mode: always

## Classic Eureka configuration
eureka:
  instance:
    preferIpAddress: false
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${server.port}
    secure-port: 443
    hostname: ${HOSTNAME:localhost}

  client:
    registerWithEureka: true
    fetchRegistry: true
    hostname: ms-operador
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

## Buscador
incidentesBuscador:
  urlRegistro: http://ms-buscador/incidente


