#spring:
spring:
  application:
    name: ms-buscador
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_URL:localhost}:5432/safepeople_buscador
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:pass}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

## Classic Eureka configuration
eureka:
  instance:
    preferIpAddress: false
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${server.port}
    secure-port: 443
    hostname: ${HOSTNAME:localhost}

  client:
    registerWithEureka: true
    fetchRegistry: true
    hostname: ms-buscador
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}